#!/bin/bash

if [ $# -ne 2 ]; then
	echo "USAGE: $0 [HOST] [PORT]"
	exit 0
fi

HOST=$1
PORT=$2

TRUST_ROOT=cert/root.crt

DID=$(cat vc/did.txt)
DID_PKEY=vc/did-private.pem
	
CERT=cert/cert.pem
CERT_PKEY=cert/private.pem
CHAIN=cert/cert-chain.crt

echo "Q" | openssl s_client -connect $HOST:$PORT -cert $CERT -key $CERT_PKEY -CAfile $TRUST_ROOT -chainCAfile $CHAIN -did_key $DID_PKEY -did $DID -did_methods ott,eth